version: "3.8"

services:

  mysql:
    build:
      context: .
      dockerfile: docker/mysql.Dockerfile
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
    restart: unless-stopped

  nginx:
    build:
      context: .
      dockerfile: docker/nginx.Dockerfile
    ports:
      - '80:80'
    depends_on:
      - phpfpm
      - mysql

  composer:
    build:
      context: .
      dockerfile: docker/composer.Dockerfile
    volumes:
      - "./codeigniter:/var/www/html:delegated"
    tty: true

  php:
    build:
      context: .
      dockerfile: docker/php-cli.Dockerfile
    volumes:
      - "./codeigniter:/var/www/html:delegated"
    tty: true

  phpfpm:
    build:
      context: .
      dockerfile: docker/php-fpm.Dockerfile
    volumes:
      - "./codeigniter:/var/www/html:delegated"